// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiLpxw23aAaSqT4b-zuhOOwL-tFYDDIJo',
    appId: '1:122320937038:web:0fa90b1d531230ae2f631f',
    messagingSenderId: '122320937038',
    projectId: 'markifootballclub',
    authDomain: 'markifootballclub.firebaseapp.com',
    storageBucket: 'markifootballclub.firebasestorage.app',
    measurementId: 'G-DHL4CGRSEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZXbzUwmFcTtKBCvI3yprOTj80wnxUcVk',
    appId: '1:122320937038:android:c61bcc9d912508552f631f',
    messagingSenderId: '122320937038',
    projectId: 'markifootballclub',
    storageBucket: 'markifootballclub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKBgMQn4wry0WdKCPU_YImk4XzRpXa4lo',
    appId: '1:122320937038:ios:5db0e0ae43bd04762f631f',
    messagingSenderId: '122320937038',
    projectId: 'markifootballclub',
    storageBucket: 'markifootballclub.firebasestorage.app',
    iosClientId: '122320937038-intec9ck8cfi9i7510dm2vu1ohq995te.apps.googleusercontent.com',
    iosBundleId: 'com.example.markfc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKBgMQn4wry0WdKCPU_YImk4XzRpXa4lo',
    appId: '1:122320937038:ios:5db0e0ae43bd04762f631f',
    messagingSenderId: '122320937038',
    projectId: 'markifootballclub',
    storageBucket: 'markifootballclub.firebasestorage.app',
    iosClientId: '122320937038-intec9ck8cfi9i7510dm2vu1ohq995te.apps.googleusercontent.com',
    iosBundleId: 'com.example.markfc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiLpxw23aAaSqT4b-zuhOOwL-tFYDDIJo',
    appId: '1:122320937038:web:0fa90b1d531230ae2f631f',
    messagingSenderId: '122320937038',
    projectId: 'markifootballclub',
    authDomain: 'markifootballclub.firebaseapp.com',
    storageBucket: 'markifootballclub.firebasestorage.app',
    measurementId: 'G-DHL4CGRSEV',
  );
}
